### ISSUE TITLE
failed to compile 1.4.1

### ISSUE THREAD

**Issue by mrehder** [mbj4668/pyang#133]
Tried to install pyang 1.4.1, using python 3.3.4 64bit on Windows 7
Got a compile error.

$ /c/Python33/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import pyang
  File "c:\pyang\pyang-master\pyang\__init__.py", line 10, in <module>
    from . import yang_parser
  File "c:\pyang\pyang-master\pyang\yang_parser.py", line 7, in <module>
    from . import statements
  File "c:\pyang\pyang-master\pyang\statements.py", line 10, in <module>
    from . import grammar
  File "c:\pyang\pyang-master\pyang\grammar.py", line 645
    def _match_stmt(ctx, stmt, (spec, canspec), canonical):
                               ^
SyntaxError: invalid syntax

any suggestions on how to resolve this?

**Comment by mbj4668** [comment]
For now, neither pyang 1.4.1 nor 1.5 can be installed using python 3.3.x or 3.4.x.
If possible install python 2.7.x and use that.

I will fix this bug though.

**Comment by mrehder** [comment]
thanks
