### ISSUE TITLE
deviation on a node instantiated from a grouping results in backtrace

### ISSUE THREAD

**Issue by jhaas-pfrc** [mbj4668/pyang#137]
Running this against the openconfig bgp model:

  import bgp { prefix bgp; }
 
 deviation /bgp:bgp/bgp:global/bgp:use-multiple-paths {
    deviate not-supported;
}

Traceback (most recent call last):
  File "/Users/jhaas/Pyang/pyang-1.5/bin/pyang", line 403, in <module>
    run()
  File "/Users/jhaas/Pyang/pyang-1.5/bin/pyang", line 279, in run
    expect_failure_error=False)
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/__init__.py", line 103, in add_module
    return self.add_parsed_module(module)
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/__init__.py", line 132, in add_parsed_module
    statements.validate_module(self, module)
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/statements.py", line 95, in validate_module
    iterate(module, phase)
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/statements.py", line 90, in iterate
    iterate(s, phase)
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/statements.py", line 90, in iterate
    iterate(s, phase)
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/statements.py", line 52, in iterate
    res = f(ctx, stmt)
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/statements.py", line 213, in <lambda>
    ('reference_3', 'deviate'):lambda ctx, s:v_reference_deviate(ctx, s),
  File "/Users/jhaas/Pyang/pyang-1.5/pyang/statements.py", line 1882, in v_reference_deviate
    idx = t.parent.substmts.index(t)
ValueError: <pyang.statements.Statement object at 0x108c7c850> is not in list

**Comment by mbj4668** [comment]
Already fixed in 5f62f9e61bb, see #115.
