### ISSUE TITLE
PYANG UML tool bug?

### ISSUE THREAD

**Issue by sunseawq** [mbj4668/pyang#154]
Installed pyang 1.4.1 on windows 7,using python 2.7.9

We found the following warning flagged when run pyang uml tool.
"
$ pyang -f uml ietf-gen-oam.yang -o goam.uml
Info: Did not find leafref target
/if:interfaces-state/if:interface/if:admin-status
Info: Did not find leafref target
/if:interfaces-state/if:interface/if:oper-status
Traceback (most recent call last):
File "c:/pyang-1.4.1/bin/pyang", line 333, in <module>
run()
File "c:/pyang-1.4.1/bin/pyang", line 328, in run
os.rename(tmpfile, o.outfile)WindowsError: [Error 183]
"
admin-status and oper-status are two leaf instances of interface data tree defined in RFC7223 we are referencing in the ietf-gen-oam module. We are not sure this is PYANG UML tool bug.

**Comment by svallin** [comment]
Hi!
Can you send me the exact YANG modules you are testing with
br Stefan

**Comment by sunseawq** [comment]
Sure, please attached.

-Qin
发件人: svallin [mailto:notifications@github.com]
发送时间: 2015年8月3日 17:19
收件人: mbj4668/pyang
抄送: Qin Wu
主题: Re: [pyang] PYANG UML tool bug? (#154)

Hi!
Can you send me the exact YANG modules you are testing with
br Stefan
