### ISSUE TITLE
Python windows replacing file has problems

### ISSUE THREAD

**Issue by vkosuri** [mbj4668/pyang#171]
When i was trying to generate output files on Windows i am getting Exception on Python 2.7

Traceback (most recent call last):
  File "C:\Python27\Scripts\pyang", line 405, in <module>
    run()
  File "C:\Python27\Scripts\pyang", line 389, in run
    os.rename(tmpfile, o.outfile)
WindowsError: [Error 183] Cannot create a file when that file already exists

And it is working fine in Linux as expected, It is completing overwriting existing output file 

I think a nice fix would be sufficent

if os.name == 'nt'
                try:
                    os.unlink(o.outfile)
                except OSError:
                    pass

**Comment by vkosuri** [comment]
and also it the temporary files are left at same place

![pyang_replace](https://cloud.githubusercontent.com/assets/13664257/10481450/47e32a2c-728e-11e5-8962-f436f3c1c981.png)
