### ISSUE TITLE
Pyang problem with utf encoded file

### ISSUE THREAD

**Issue by xianglisegue** [mbj4668/pyang#221]
Hi 

I downloaded the following pyang example yang modules from:
https://raw.githubusercontent.com/mbj4668/pyang/master/doc/tutorial/examples/turing-machine.yang

https://raw.githubusercontent.com/mbj4668/pyang/master/doc/tutorial/examples/second-tape.yang

1. Using Pyang 1.5
All work fine.

2. Using pyang 1.6, I got error:

[xiangli@localhost pyang-pyang-1.6]$ pyang  turing-machine.yang
Traceback (most recent call last):
  File "/home/xiangli/Downloads/pyang-pyang-1.6/bin/pyang", line 420, in <module>
    run()
  File "/home/xiangli/Downloads/pyang-pyang-1.6/bin/pyang", line 290, in run
    expect_failure_error=False)
  File "/home/xiangli/Downloads/pyang-pyang-1.6/pyang/__init__.py", line 100, in add_module
    module.i_adler32 = zlib.adler32(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 3906: ordinal not in range(128)

3
 Using pyang master, initially it appears they validate fine:
[xiangli@localhost pyang-master]$ pyang  turing-machine.yang
[xiangli@localhost pyang-master]$ pyang  second-tape.yang 

But if first generate a yin format file turing-machine.yin and then validate second-tape.yang, I got ane rror. I showed steps and results below:

$pyang -f yin turing-machine.yang >  turing-machine.yin
$pyang second-tape.yang 
Traceback (most recent call last):
  File "/home/xiangli/Downloads/pyang-master/bin/pyang", line 434, in <module>
    run()
  File "/home/xiangli/Downloads/pyang-master/bin/pyang", line 298, in run
    expect_failure_error=False)
  File "/home/xiangli/Downloads/pyang-master/pyang/__init__.py", line 100, in add_module
    return self.add_parsed_module(module)
  File "/home/xiangli/Downloads/pyang-master/pyang/__init__.py", line 122, in add_parsed_module
    statements.validate_module(self, module)
  File "/home/xiangli/Downloads/pyang-master/pyang/statements.py", line 418, in validate_module
    iterate(module, phase)
  File "/home/xiangli/Downloads/pyang-master/pyang/statements.py", line 375, in iterate
    res = f(ctx, stmt)
  File "/home/xiangli/Downloads/pyang-master/pyang/statements.py", line 208, in <lambda>
    ('import', 'module'):lambda ctx, s: v_import_module(ctx, s),
  File "/home/xiangli/Downloads/pyang-master/pyang/statements.py", line 596, in v_import_module
    module = add_module(i)
  File "/home/xiangli/Downloads/pyang-master/pyang/statements.py", line 580, in add_module
    m = ctx.get_module(modulename, rev)
  File "/home/xiangli/Downloads/pyang-master/pyang/__init__.py", line 134, in get_module
    (revision, _handle) = self._get_latest_rev(self.revs[modulename])
  File "/home/xiangli/Downloads/pyang-master/pyang/__init__.py", line 142, in _get_latest_rev
    self._ensure_revs(revs)
  File "/home/xiangli/Downloads/pyang-master/pyang/__init__.py", line 174, in _ensure_revs
    module = p.parse(self, ref, text)
  File "/home/xiangli/Downloads/pyang-master/pyang/yin_parser.py", line 88, in parse
    self.parser.Parse(text, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 5318: ordinal not in range(128)

The problem has something to do a unicode char contained in the turing-machine.yang downloaded. The file opens fine in vi, notepad, etc, but if you check its encoding:
check file encoding:
$file -bi turing-machine.yang
text/plain; charset=utf-8

and trying to convert to ascii encoding:
$iconv -f utf-8 -t ascii turing-machine.yang t.yang
...
       1. Put the control unit into the initial stateiconv: illegal input sequence at position 3906

So should pyang handle this or the unicode char is wrong to be there?

Best
XIang

**Comment by abravalheri** [comment]
Apparently this issue is related to [`pyexpat`](https://docs.python.org/2/library/pyexpat.html), which cannot handle python unicode string (at list in python 2.7) ([reference](https://mail.python.org/pipermail/python-list/2001-December/070358.html)).

I have performed the following test:

- Check python version
```shell
python -V
# => Python 2.7.6
```

- Create a file `amodule.yang`
```yang
module amodule {
  namespace "urn:test:amodule";
  prefix "amodule";

  organization "organização güi";
  contact "àéïç¢ô";

  grouping x {
    leaf y { type string; }
  }

  rpc run {
    input { uses x; }
    output { uses x; }
  }
}
```

- Ensure `pyang -f tree amodule.yang` does not result in error

- Convert it to yin
```shell
pyang -f yin amodule.yang -o amodule.yin
```

- Try to use yin as input
```shell
pyang -f tree amodule.yin
# =>
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 434, in <module>
    run()
  File "/usr/local/bin/pyang", line 298, in run
    expect_failure_error=False)
  File "/usr/local/lib/python2.7/dist-packages/pyang/__init__.py", line 72, in add_module
    module = p.parse(self, ref, text)
  File "/usr/local/lib/python2.7/dist-packages/pyang/yin_parser.py", line 88, in parse
    self.parser.Parse(text, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 255-256: ordinal not in range(128)
```

- Test the expat xml parser from interactive python:
```python
from xml.parsers import expat
import io
fp = io.open('amodule.yin', encoding='utf-8')
text = fp.read()
parser = expat.ParserCreate('UTF-8')
parser.Parse(text, True)
# =>
# Traceback (most recent call last):
#   File "<input>", line 1, in <module>
#     parser.Parse(text)
# UnicodeEncodeError: 'ascii' codec can't encode characters in position 255-256: ordinal not in range(128)
```

In my point of view, this test is related to the @xianglisegue description in the following sense:

- when `pyang` resolves `import` statements, `yin` files take precedence over `yang` files
- `xml.parsers.expat` (used by `pyang`) cannot parse unicode strings (at least in python 2.7) and results in an `UnicodeEncodeError`
- If no `yin` file is present, the `import` statement is resolved using UTF-8 `yang` file, which `pyang` has no problems in parsing

A workaround could be converting unicode string to ascii, but this change will remove complex characters.
```python
ascii_text = text.encode('ascii', 'ignore')
self.parser.Parse(ascii_text, True)
```
