### ISSUE TITLE
Error in using pyang

### ISSUE THREAD

**Issue by ashishk1994** [mbj4668/pyang#223]
Hi,

I am using below version of pip,  pip --version is giving
`pip 7.1.2 from /usr/local/lib/python3.2/dist-packages (python 3.2)`

I installed pyang using 
`pip install pyang`

Now when I tried to compile the yang file using pyang I am getting following error:

Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 8, in <module>
    import pyang
  File "/usr/local/lib/python3.2/dist-packages/pyang/**init**.py", line 10, in <module>
    from . import yang_parser
  File "/usr/local/lib/python3.2/dist-packages/pyang/yang_parser.py", line 177
    if (type(nstr) != type(u'')):
                             ^
SyntaxError: invalid syntax

Can you please help me with this.

**Comment by paulnice** [comment]
Try to run pyang with python 2.

**Comment by mbj4668** [comment]
I think this is resolved in later versions.
