### ISSUE TITLE
XPATH parsing of node/function after multiply is broken

### ISSUE THREAD

**Issue by wivory** [mbj4668/pyang#234]
pyang 1.6 is failing to parse the following must statements:

must '3 * foo';
must '10 * number("11")';

Reported error is: <filename>:<line>: error: XPath syntax error: 29: unknown operator foo

If you reverse the order of the operands it works fine.

Additionally, if you run in strict mode, then instead of getting a single line error as above, you get a full traceback like this:

01:29:15 ~$ pyang --strict *.yang
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 4, in <module>
    __import__('pkg_resources').run_script('pyang==1.6', 'pyang')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/EGG-INFO/scripts/pyang", line 420, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/EGG-INFO/scripts/pyang", line 290, in run
    expect_failure_error=False)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/__init__.py", line 103, in add_module
    return self.add_parsed_module(module)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/__init__.py", line 132, in add_parsed_module
    statements.validate_module(self, module)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 95, in validate_module
    iterate(module, phase)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 90, in iterate
    iterate(s, phase)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 90, in iterate
    iterate(s, phase)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 90, in iterate
    iterate(s, phase)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 90, in iterate
    iterate(s, phase)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 52, in iterate
    res = f(ctx, stmt)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 222, in <lambda>
    ('strict', 'must'):lambda ctx, s: v_strict_xpath(ctx, s),
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/statements.py", line 2037, in v_strict_xpath
    toks = xpath.tokens(stmt.arg)
  File "/usr/local/lib/python2.7/dist-packages/pyang-1.6-py2.7.egg/pyang/xpath.py", line 87, in tokens
    raise SyntaxError(e)
SyntaxError: 29: unknown operator foo

I can work around this by simply reordering the operands, but would be good to get this fixed.

Thanks,

William

**Comment by wivory** [comment]
Thanks for fixing this so quickly.  Any idea when the next pyang release will be?

**Comment by mbj4668** [comment]
wivory <notifications@github.com> wrote:
> Thanks for fixing this so quickly.  Any idea when the next pyang release will be?

Within the next few days; maybe even today.


/martin
