### ISSUE TITLE
missing attribute of PathTypeSpec

### ISSUE THREAD

**Issue by llhotka** [mbj4668/pyang#278]
The following exception is raised inside the *jsonxsl* plugin but after removing the statement ``yang-version 1.1;`` everything is fine. This indicates that the problem is most likely not in the *jsonxsl* plugin but rather in 1.1 version of the ``PathTypeSpec`` object.

```
module test {
  yang-version 1.1;
  namespace "http://example.com/test";
  prefix t;

  typedef foo-ref {
    type leafref {
      path "/foo/clef";
    }
  }

  list foo {
    key "clef";
    leaf clef {
      type string;
    }
  }
  leaf bar {
    type foo-ref;
  }
}
$ pyang -f jsonxsl test.yang
Traceback (most recent call last):
  File "/Users/lhotka/bin/pyang", line 434, in <module>
    run()
  File "/Users/lhotka/bin/pyang", line 408, in run
    emit_obj.emit(ctx, modules, fd)
  File "/Users/lhotka/lib/python/pyang/plugins/jsonxsl.py", line 93, in emit
    self.process_module(module)
  File "/Users/lhotka/lib/python/pyang/plugins/jsonxsl.py", line 113, in process_module
    self.process_children(yam, "//nc:*", 1)
  File "/Users/lhotka/lib/python/pyang/plugins/jsonxsl.py", line 167, in process_children
    self.type_param(ch, ct)
  File "/Users/lhotka/lib/python/pyang/plugins/jsonxsl.py", line 175, in type_param
    types = self.get_types(node)
  File "/Users/lhotka/lib/python/pyang/plugins/jsonxsl.py", line 219, in get_types
    resolve(node.search_one("type"))
  File "/Users/lhotka/lib/python/pyang/plugins/jsonxsl.py", line 216, in resolve
    resolve(typ.i_typedef.search_one("type"))
  File "/Users/lhotka/lib/python/pyang/plugins/jsonxsl.py", line 209, in resolve
    resolve(typ.i_type_spec.i_target_node.search_one("type"))
AttributeError: 'PathTypeSpec' object has no attribute 'i_target_node'
```

**Comment by mbj4668** [comment]
In YANG 1.1, unprefixed paths in a leafref work like groupings - they are resolved when they are used.  This means that the typedef doesn't have a target node.  However, the leaf that refer to the typedef has  a target node.  So, it is a bug in jsonxsl.py.

**Comment by mbj4668** [comment]
See the comment in validate_leafref_path in statements.py
