### ISSUE TITLE
error scripts pyang 

### ISSUE THREAD

**Issue by aksenofontova** [mbj4668/pyang#283]
Hello
I need help too. Can't configure netopeer Ubuntu 15.04
I pulled from git clone https://github.com/CESNET/libnetconf and netopeer. Libnetconf is ok.
But I have errors when try install netopeer, like this
/netopeer/server$ ./configure
checking for pkg-config... /usr/bin/pkg-config
checking for roff2html... no
checking for distro... ubuntu
configure: WARNING: Unsupported Linux distro "ubuntu", only RHEL and SUSE are fully supported.
checking pkg-config is at least version 0.9.0... yes
checking for LIBNETCONF... yes
checking for uname... yes
checking for host architecture... x86_64
checking for lnctool... yes
checking python module: os... yes
checking python module: copy... yes
checking python module: curses... yes
checking python module: libxml2... yes
checking python module: subprocess... yes
checking python module: re... yes
checking python module: string... yes
checking python module: argparse... yes
checking python module: xml... yes
checking for rpmbuild... rpmbuild
checking for clang... no
checking for llvm-gcc... llvm-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether llvm-gcc accepts -g... yes
checking for llvm-gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for main in -lxml2... yes
checking for xml2-config... yes
checking for library containing ncntf_dispatch_receive... none required
checking for nc_session_accept_libssh_channel in -lnetconf... yes
checking for library containing ssh_pki_key_ecdsa_name... -lssh
checking for library containing crypt... -lcrypt
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
configure: generating validation files...
Traceback (most recent call last):
File "/usr/local/bin/pyang", line 4, in 
import('pkg_resources').run_script('pyang==1.7.1', 'pyang')
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 698, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 1616, in run_script
exec(code, namespace, namespace)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/EGG-INFO/scripts/pyang", line 439, in 
run()
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/EGG-INFO/scripts/pyang", line 408, in run
emit_obj.emit(ctx, modules, fd)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 89, in emit
emit_dsdl(ctx, modules, fd)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 98, in emit_dsdl
ctx.opts.dsdl_record_defs, debug=0)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 402, in from_modules
self.handle_substmts(module, self.data, gpset)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 908, in handle_substmts
self.handle_stmt(sub, p_elem, pset)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 903, in handle_stmt
method(stmt, p_elem, pset)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 1102, in rpc_stmt
self.handle_substmts(inst, elem, pset)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 908, in handle_substmts
self.handle_stmt(sub, p_elem, pset)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 903, in handle_stmt
method(stmt, p_elem, pset)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 1030, in leaf_stmt
self.leafref_type(stmt, elem)
File "/usr/local/lib/python2.7/dist-packages/pyang-1.7.1-py2.7.egg/pyang/translators/dsdl.py", line 1241, in leafref_type
cnode = cnode.i_leafref_ptr[0]
TypeError: 'NoneType' object has no attribute 'getitem'
Command 'pyang -p /home/user/netopeer/server/config/ -f dsdl --dsdl-no-documentation --dsdl-no-dublin-core -o /tmp/dsdlWqqUTf.dsdl /home/user/netopeer/server/config/netopeer-cfgnetopeer.yin --features netopeer-cfgnetopeer:dynamic-modules,ssh' failed (1)
configure: error: Generating validation files for netopeer-cfgnetopeer failed.

What can i do with this?

**Comment by llhotka** [comment]
This is fixed in 04e57a707b4ba51f588bf9928f182696feb2bc27.

**Comment by aksenofontova** [comment]
Thanks a lot, it helped)
