### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by llhotka** [mbj4668/pyang#300]
```
$ cat devext.yang 
module devext {
  namespace "http://example.com/devext";
  prefix de;
  import ietf-interfaces {
    prefix if;
  }
  extension foo;
  deviation "/if:interfaces" {
    deviate "add" {
      de:foo;
    }
  }
}
$ pyang devext.yang 
Traceback (most recent call last):
  File "/Users/lhotka/bin/pyang", line 439, in <module>
    run()
  File "/Users/lhotka/bin/pyang", line 298, in run
    expect_failure_error=False)
  File "/Users/lhotka/lib/python/pyang/__init__.py", line 100, in add_module
    return self.add_parsed_module(module)
  File "/Users/lhotka/lib/python/pyang/__init__.py", line 122, in add_parsed_module
    statements.validate_module(self, module)
  File "/Users/lhotka/lib/python/pyang/statements.py", line 420, in validate_module
    iterate(module, phase)
  File "/Users/lhotka/lib/python/pyang/statements.py", line 415, in iterate
    iterate(s, phase)
  File "/Users/lhotka/lib/python/pyang/statements.py", line 415, in iterate
    iterate(s, phase)
  File "/Users/lhotka/lib/python/pyang/statements.py", line 377, in iterate
    res = f(ctx, stmt)
  File "/Users/lhotka/lib/python/pyang/statements.py", line 253, in <lambda>
    ('reference_3', 'deviate'):lambda ctx, s:v_reference_deviate(ctx, s),
  File "/Users/lhotka/lib/python/pyang/statements.py", line 2095, in v_reference_deviate
    if t.keyword not in _valid_deviations[c.keyword]:
KeyError: (u'devext', u'foo')
```

**Comment by BalazsLengyel** [comment]
IMHO this should not cause a crash it is valid YANG.

**Comment by mbj4668** [comment]
Balazs, I will pretend I didn't read that...
