### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by satyacube** [mbj4668/pyang#308]
While using the '--check-update-from' functionality, for certain YANG models I see the following error:

04:59:07: DEBUG PYANG returned a non-zero exit code (1)

04:59:07: DEBUG Printing the PYANG report...

04:59:07: DEBUG --------------------------------------------------

04:59:07: DEBUG Traceback (most recent call last):

04:59:07: DEBUG   File "/auto/xr-pi/pyang/bin/pyang", line 444, in <module>

04:59:07: DEBUG     run()

04:59:07: DEBUG   File "/auto/xr-pi/pyang/bin/pyang", line 355, in run

04:59:07: DEBUG     p.post_validate_ctx(ctx, modules)

04:59:07: DEBUG   File "/auto/xr-pi/pyang/pyang/plugins/check_update.py", line 125, in post_validate_ctx

04:59:07: DEBUG     check_update(ctx, ctx.opts.check_update_from, modules[0])

04:59:07: DEBUG IndexError: list index out of range

**Comment by kuthulas** [comment]
I have the same issue. Could someone explain when can modules be empty at check_update(ctx, ctx.opts.check_update_from, modules[0]), and why does pyang not catch this?

**Comment by mbj4668** [comment]
Can you include the modules you are checking, and the exact command line you are using so the bug can be reproduced?
