### ISSUE TITLE
pyang 1.7.4 crashes generating sample-xml-skeleton

### ISSUE THREAD

**Issue by iffy50** [mbj4668/pyang#381]
Hi,

I'm seeing a crash when I try and generate a sample-xml-skeleton

$ pyang -f sample-xml-skeleton ietf-dhcpv6-server.yang
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 450, in <module>
    run()
  File "/usr/local/bin/pyang", line 419, in run
    emit_obj.emit(ctx, modules, fd)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 122, in emit
    self.process_children(yam, self.top, None, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 141, in process_children
    self.node_handler[ch.keyword](ch, elem, module, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 152, in container
    self.process_children(node, nel, newm, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 141, in process_children
    self.node_handler[ch.keyword](ch, elem, module, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 152, in container
    self.process_children(node, nel, newm, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 141, in process_children
    self.node_handler[ch.keyword](ch, elem, module, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 152, in container
    self.process_children(node, nel, newm, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 141, in process_children
    self.node_handler[ch.keyword](ch, elem, module, path)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 194, in leaf_list
    self.list_comment(node, nel, minel)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/sample-xml-skeleton.py", line 232, in list_comment
    ",".join([k.arg for k in node.i_key])))
AttributeError: 'Statement' object has no attribute 'i_key'

The module seems to be OK, in that I can create tree output without getting any errors/warnings. I have also been able to successfully create the xml-skeleton by dropping back to pyang 1.7.3.

Any clues?
thanks,
Ian

**Comment by llhotka** [comment]
It looks like this problem doesn't show up with the current development version on GitHub. @iffy50, can you test it with that version?
