### ISSUE TITLE
jsonxsl creation for a file errors out

### ISSUE THREAD

**Issue by nkaliape** [mbj4668/pyang#393]
pyang --lax-quote-checks --plugindir $PYBINDPLUGIN -f jsonxsl -o $xslfile $file 
file =  openconfig-aaa-tacacs.yang version 0.3.0

Note: pybind and jtox both worked but only jsonxsl failed.

processing openconfig-aaa-tacacs.yang ....@@@@
Traceback (most recent call last):
  File "/home/nkaliape/testenv/bin/pyang", line 450, in <module>
    run()
  File "/home/nkaliape/testenv/bin/pyang", line 419, in run
    emit_obj.emit(ctx, modules, fd)
  File "/home/nkaliape/testenv/local/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 224, in emit
    build_pybind(ctx, modules, fd)
  File "/home/nkaliape/testenv/local/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 411, in build_pybind
    build_identities(ctx, defn['identity'])
  File "/home/nkaliape/testenv/local/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 450, in build_identities
    idstore.build_store_from_definitions(ctx, defnd)
  File "/home/nkaliape/testenv/local/lib/python2.7/site-packages/pyangbind/helpers/identity.py", line 115, in build_store_from_definitions
    base_id = self.find_identity_by_source_name(parent_module.arg, base_name)
AttributeError: 'NoneType' object has no attribute 'arg'

**Comment by llhotka** [comment]
I can't reproduce the problem. Can you try it with the latest dev version of pyang from GitHub?

BTW, the `openconfig-aaa-tacacs` module doesn't define any data nodes, so it is pointless to use the `jsonxsl` plugin on it.

**Comment by nkaliape** [comment]
With latest version - I'm NOT hitting any issue. closing the issue.
