### ISSUE TITLE
json config validation using json2xml fails with stacktrace

### ISSUE THREAD

**Issue by ganeshrn** [mbj4668/pyang#402]
Validating invalid json openconfig interface configuration against openconfig interface yang model displays wrong error message with stacktrace.

`$ python --version`
```
Python 3.5.2
```

Actual result:
`$ json2xml -t config interfaces.jtox interfaces-config.json`
```
Traceback (most recent call last):
  File "/Users/gnalawad/aenv_py3/bin/json2xml", line 441, in <module>
    sys.exit(main())
  File "/Users/gnalawad/aenv_py3/bin/json2xml", line 431, in main
    trans.translate(jfile, root_el)
  File "/Users/gnalawad/aenv_py3/bin/json2xml", line 130, in translate
    return self.translate_obj(d, None, self.tree, xml_root, "/")
  File "/Users/gnalawad/aenv_py3/bin/json2xml", line 170, in translate_obj
    new_path + "/")
  File "/Users/gnalawad/aenv_py3/bin/json2xml", line 186, in translate_obj
    el.remove(knode)
TypeError: remove() argument must be xml.etree.ElementTree.Element, not None
```

Expected result:
`$ json2xml -t config interfaces.jtox interfaces-config.json`
```
json2xml: error at /openconfig-interfaces:interfaces/interface/0/ - missing key 'openconfig-interfaces:name'
```

Invalid interface config:
`$ cat interfaces-config.json`
```
{
"openconfig-interfaces:interfaces": {
  "interface": [
    {
        "config":
            {
                "description": "test openconfig",
                "name" : "GigabitEthernet0/0/0/2"
            }

     }
  ]
  }
}
```

`$ cat interfaces.jtox`
```
{"tree": {"openconfig-interfaces:interfaces": ["container", {"interface": ["list", {"state": ["container", {"description": ["leaf", "string"], "admin-status": ["leaf", "enumeration"], "oper-status": ["leaf", "enumeration"], "enabled": ["leaf", "boolean"], "mtu": ["leaf", "uint16"], "ifindex": ["leaf", "uint32"], "last-change": ["leaf", "uint32"], "counters": ["container", {"out-octets": ["leaf", "uint64"], "out-errors": ["leaf", "uint64"], "in-multicast-pkts": ["leaf", "uint64"], "out-unicast-pkts": ["leaf", "uint64"], "in-errors": ["leaf", "uint64"], "out-multicast-pkts": ["leaf", "uint64"], "in-discards": ["leaf", "uint64"], "last-clear": ["leaf", "string"], "in-unicast-pkts": ["leaf", "uint64"], "out-broadcast-pkts": ["leaf", "uint64"], "out-discards": ["leaf", "uint64"], "in-broadcast-pkts": ["leaf", "uint64"], "in-unknown-protos": ["leaf", "uint32"], "in-octets": ["leaf", "uint64"]}], "type": ["leaf", "identityref"], "name": ["leaf", "string"]}], "hold-time": ["container", {"state": ["container", {"down": ["leaf", "uint32"], "up": ["leaf", "uint32"]}], "config": ["container", {"down": ["leaf", "uint32"], "up": ["leaf", "uint32"]}]}], "config": ["container", {"enabled": ["leaf", "boolean"], "description": ["leaf", "string"], "type": ["leaf", "identityref"], "name": ["leaf", "string"], "mtu": ["leaf", "uint16"]}], "name": ["leaf", "string"], "subinterfaces": ["container", {"subinterface": ["list", {"index": ["leaf", "uint32"], "state": ["container", {"index": ["leaf", "uint32"], "name": ["leaf", "string"], "oper-status": ["leaf", "enumeration"], "enabled": ["leaf", "boolean"], "counters": ["container", {"out-octets": ["leaf", "uint64"], "out-errors": ["leaf", "uint64"], "in-multicast-pkts": ["leaf", "uint64"], "out-unicast-pkts": ["leaf", "uint64"], "in-errors": ["leaf", "uint64"], "out-multicast-pkts": ["leaf", "uint64"], "in-discards": ["leaf", "uint64"], "last-clear": ["leaf", "string"], "in-unicast-pkts": ["leaf", "uint64"], "out-broadcast-pkts": ["leaf", "uint64"], "out-discards": ["leaf", "uint64"], "in-broadcast-pkts": ["leaf", "uint64"], "in-unknown-protos": ["leaf", "uint32"], "in-octets": ["leaf", "uint64"]}], "ifindex": ["leaf", "uint32"], "last-change": ["leaf", "uint32"], "unnumbered": ["leaf", "uint32"], "admin-status": ["leaf", "enumeration"], "description": ["leaf", "string"]}], "config": ["container", {"index": ["leaf", "uint32"], "unnumbered": ["leaf", "uint32"], "enabled": ["leaf", "boolean"], "name": ["leaf", "string"], "description": ["leaf", "string"]}]}, [["openconfig-interfaces", "index"]]]}]}, [["openconfig-interfaces", "name"]]]}]}, "modules": {"openconfig-extensions": ["oc-ext", "http://openconfig.net/yang/openconfig-ext"], "ietf-yang-types": ["yang", "urn:ietf:params:xml:ns:yang:ietf-yang-types"], "openconfig-interfaces": ["ocif", "http://openconfig.net/yang/interfaces"], "ietf-interfaces": ["if", "urn:ietf:params:xml:ns:yang:ietf-interfaces"]}, "annotations": {}}
```

**Comment by llhotka** [comment]
How did you generate the `jtox` file? What is your data model?

**Comment by ganeshrn** [comment]
I am fetching OpenConfig interface yang model from iosxr device. The yang model can be found here
https://gist.github.com/ganeshrn/d1b7f3bfc013e8930a6fd78ee31319f8

After that run the pyang command to generate jtox file
```
pyang -f jtox -o interfaces.jtox openconfig-interfaces.yang -p /home/network/openconfig/public/release/models:/home/network/pyang/modules
```

**Comment by ganeshrn** [comment]
The commit you referenced does not seem to fix the issue properly. With your patch applied I am getting below error on Python 2.7
```
$ json2xml -t config interfaces.jtox interfaces-config.json
Traceback (most recent call last):
  File "/usr/local/bin/json2xml", line 441, in <module>
    sys.exit(main())
  File "/usr/local/bin/json2xml", line 431, in main
    trans.translate(jfile, root_el)
  File "/usr/local/bin/json2xml", line 130, in translate
    return self.translate_obj(d, None, self.tree, xml_root, "/")
  File "/usr/local/bin/json2xml", line 170, in translate_obj
    new_path + "/")
  File "/usr/local/bin/json2xml", line 186, in translate_obj
    el.remove(knode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 337, in remove
    self._children.remove(element)
```

FYI I have raised a PR https://github.com/mbj4668/pyang/pull/403 to fix this issue and it is working as expected on py2.X and py3.X versions

**Comment by ganeshrn** [comment]
I have spent some time and effort in testing and fixing this issue. I hope the PR https://github.com/mbj4668/pyang/pull/403 is at least reviewed before pushing a similar fix.
