### ISSUE TITLE
issue with right single quotation mark

### ISSUE THREAD

**Issue by mark-grayson** [mbj4668/pyang#447]
YANG descriptions that include _right single quotation mark_ (&#8217;) instead of _single quote_ (&#39;) cause AttributeError

**Comment by mark-grayson** [comment]
Hi Martin

The attached model has ascii code 8217 on lines 134/5 and 217/8.

This generates the following


pyang -f tree xran-hardware.yang

Traceback (most recent call last):

  File "~/NSO/ncs4.7/netsim/confd/lib/pyang/bin/pyang", line 411, in <module>

    run()

  File "~/NSO/ncs4.7/netsim/confd/lib/pyang/bin/pyang", line 283, in run

    expect_failure_error=False)

  File "/Library/Python/2.7/site-packages/pyang-1.7.4-py2.7.egg/pyang/__init__.py", line 75, in add_module

    module = p.parse(self, ref, text)

  File "/Library/Python/2.7/site-packages/pyang-1.7.4-py2.7.egg/pyang/yang_parser.py", line 263, in parse

    stmt = self._parse_statement(None)

  File "/Library/Python/2.7/site-packages/pyang-1.7.4-py2.7.egg/pyang/yang_parser.py", line 314, in _parse_statement

    substmt = self._parse_statement(stmt)

  File "/Library/Python/2.7/site-packages/pyang-1.7.4-py2.7.egg/pyang/yang_parser.py", line 314, in _parse_statement

    substmt = self._parse_statement(stmt)

  File "/Library/Python/2.7/site-packages/pyang-1.7.4-py2.7.egg/pyang/yang_parser.py", line 299, in _parse_statement

    arg = self.tokenizer.get_string()

  File "/Library/Python/2.7/site-packages/pyang-1.7.4-py2.7.egg/pyang/yang_parser.py", line 190, in get_string

    return u''.join(strs)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)

When I do a search and replace from ascii code 8217 to 39 the output is as expected


module: xran-hardware

  augment /hw:hardware/hw:component:

    +--ro label-content

    |  +--ro model-name?      boolean

    |  +--ro serial-number?   boolean

    +--ro product-code             string

    +--rw energy-saving-enabled?   boolean {ENERGYSAVING}?

  augment /hw:hardware/hw:component:

    +--rw xran-name    -> /hw:hardware/component/name

  augment /hw:hardware/hw:component/hw:state:

    +--ro power-state?          energysaving-state {ENERGYSAVING}?

    +--ro availability-state?   availability-type

  augment /hw:hardware-state-oper-enabled:

    +--ro availability-state?   -> /hw:hardware/component/state/xran-hw:availability-state

  augment /hw:hardware-state-oper-disabled:

    +--ro availability-state?   -> /hw:hardware/component/state/xran-hw:availability-state

Cheers,
Mark

**Comment by mbj4668** [comment]
You forgot to attach the module.  But please try with the latest version of pyang.  The version that is bundled with confd is very old, and it is only bundled b/c it is used in some build scripts.  For any other usage, we recommend that you get the latest version from github.
