### ISSUE TITLE
while compile opconfig yang files, a lot of errors.

### ISSUE THREAD

**Issue by Sharkjuice** [mbj4668/pyang#453]
the openconfig yang files: 
https://github.com/CiscoDevNet/ydk-py/tree/master/openconfig/ydk/models/openconfig/_yang

many errors, for examples:
iana-if-type.yang ......
Traceback (most recent call last):
  File "/usr/bin/pyang", line 450, in <module>
    run()
  File "/usr/bin/pyang", line 419, in run
    emit_obj.emit(ctx, modules, fd)
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 222, in emit
    build_pybind(ctx, modules, fd)
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 406, in build_pybind
    build_identities(ctx, defn['identity'])
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 446, in build_identities
    idstore.build_store_from_definitions(ctx, defnd)
  File "/usr/lib/python2.7/site-packages/pyangbind/helpers/identity.py", line 75, in build_store_from_definitions
    mod_ref_prefixes = module_import_prefixes(ctx)
  File "/usr/lib/python2.7/site-packages/pyangbind/helpers/misc.py", line 24, in module_import_prefixes
    for mod in ctx.modules:
RuntimeError: dictionary changed size during iteration

**Comment by mbj4668** [comment]
this seems to be an issue with pyangbind.
