### ISSUE TITLE
Exception with --check-update-from

### ISSUE THREAD

**Issue by abhikeshav** [mbj4668/pyang#459]
Steps to reproduce:
Install pyang
```
pip list | grep pyang
pyang            1.6    

```
Clone repo
```shell
git clone https://github.com/YangModels/yang.git
cd yang/vendor/cisco/xr/611
```
Run command
```shell

~/yang/vendor/cisco/xr/611 > pyang --check-update-from=Cisco-IOS-XR-infra-policymgr-oper.yang -P ../601 Cisco-IOS-XR-infra-policymgr-oper.yang
Traceback (most recent call last):
  File "/Users/wxyz/p/bin/pyang", line 420, in <module>
    run()
  File "/Users/wxyz/p/bin/pyang", line 344, in run
    p.post_validate_ctx(ctx, modules)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 124, in post_validate_ctx
    check_update(ctx, ctx.opts.check_update_from, modules[0])
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 186, in check_update
    chk_grouping(olds, newmod, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 256, in chk_grouping
    chk_i_children(olds, news, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 334, in chk_child
    chk_list(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 535, in chk_list
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 334, in chk_child
    chk_list(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 535, in chk_list
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 334, in chk_child
    chk_list(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 535, in chk_list
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 334, in chk_child
    chk_list(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 535, in chk_list
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 334, in chk_child
    chk_list(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 535, in chk_list
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 334, in chk_child
    chk_list(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 535, in chk_list
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 334, in chk_child
    chk_list(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 535, in chk_list
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 332, in chk_child
    chk_container(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 529, in chk_container
    chk_i_children(old, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 302, in chk_i_children
    chk_child(oldch, new, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 326, in chk_child
    chk_when(oldch, newch, ctx)
  File "/Users/wxyz/p/lib/python3.7/site-packages/pyang/plugins/check_update.py", line 397, in chk_when
    newwhen.remove(neww)
ValueError: list.remove(x): x not in list

```

**Comment by mbj4668** [comment]
pyang 1.6 is three years old.  the current version is 1.7.8.  could you try with the current version?

**Comment by abhikeshav** [comment]
Unable to reproduce with latest pyang
