### ISSUE TITLE
pyang memory error

### ISSUE THREAD

**Issue by rampolisetty** [mbj4668/pyang#500]
When I use pyang with a large module, it fails with memory error:

Traceback (most recent call last):
  File "/usr/libexec/ui/pyang", line 444, in <module>
    run()
  File "/usr/libexec/ui/pyang", line 274, in run
    module = ctx.add_module('<stdin>', text)
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/__init__.py", line 101, in add_module
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/__init__.py", line 123, in add_parsed_module
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 420, in validate_module
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 377, in iterate
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 228, in <lambda>
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1405, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1394, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1436, in v_expand_1_uses
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1394, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1436, in v_expand_1_uses
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1394, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1436, in v_expand_1_uses
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1394, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1436, in v_expand_1_uses
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1394, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1436, in v_expand_1_uses
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1403, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1394, in v_expand_1_children
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 1523, in v_expand_1_uses
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 2809, in copy
  File "../../../../../../../src/dist/python-add-ons/pyang/pyang/statements.py", line 2792, in copy
MemoryError

Is this a known issue? If not how to fix this, I am planning to have our own local change following: 

import resource

rsrc = resource.RLIMIT_DATA
soft, hard = resource.getrlimit(rsrc)
print 'Soft limit starts as  :', soft

resource.setrlimit(rsrc, (1024 * 1024 * 512, hard)) #limit to 512M (if needed more)

soft, hard = resource.getrlimit(rsrc)
print 'Soft limit changed to :', soft

We use pyang 1.7.3.

**Comment by mbj4668** [comment]
This may be fixed in 1.7.5 and later, or 1.7.8 and later, see #382 and  #463.
