### ISSUE TITLE
AttributeError: 'str' object has no attribute 'parent'

### ISSUE THREAD

**Issue by niktto** [mbj4668/pyang#518]
Hi!

When I want to validate my yang files using pyang 2.1 or 2.0.1 (didn't yet test on other versions) I get a weird AttributeError:

```
Traceback (most recent call last):
  File "(...)/bin/pyang", line 493, in <module>
    run()
  File "(...)/bin/pyang", line 372, in run
    ctx.validate()
  File "(...)/lib/python3.8/site-packages/pyang/__init__.py", line 338, in validate
    statements.validate_module(self, m)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 409, in validate_module
    iterate(module, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 366, in iterate
    res = f(ctx, stmt)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 191, in <lambda>
    ('import', 'module'):lambda ctx, s: v_import_module(ctx, s),
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 612, in v_import_module
    submodule = add_module(i)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 597, in add_module
    validate_module(ctx, m)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 409, in validate_module
    iterate(module, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 401, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 397, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 397, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 397, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 401, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 366, in iterate
    res = f(ctx, stmt)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 233, in <lambda>
    ('reference_2', 'when'):lambda ctx, s:v_reference_when(ctx, s),
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 2053, in v_reference_when
    v_xpath(ctx, stmt)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 2062, in v_xpath
    xpath.v_xpath(ctx, stmt, node)
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 84, in v_xpath
    chk_xpath_expr(ctx, stmt.i_orig_module, stmt.pos, node, node, q)
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 106, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[2])
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 99, in chk_xpath_expr
    chk_xpath_path(ctx, mod, pos, initial, 'root', q[1])
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 249, in chk_xpath_path
    p = data_node_up(node)
  File "(...)/lib/python3.8/site-packages/pyang/util.py", line 169, in data_node_up
    p = node.parent
AttributeError: 'str' object has no attribute 'parent'
```

`node` is just a string `"root"`. Is this supposed to happen? I have a hard time debugging this (found the dependency yang file that causes this but it looks good on the surface).

I would be very grateful for any feedback.

**Comment by mbj4668** [comment]
Obviously a bug.  Please attach the files needed to reproduce this, and instructions.

**Comment by niktto** [comment]
### File test.yang

> Original file is more complex but I managed to prepare a file that is small and still causes same issue

```
submodule testFile {
    augment "/test" {
        container x {
            container test-1 {
                leaf tcp-profile {
                    when "/../../test/protocol = 'test'";
                }
            }
        }
    }
}
```

### Command:
`pyang test.yang`

### Result:
```
Traceback (most recent call last):
  File "(...)/bin/pyang", line 493, in <module>
    run()
  File "(...)/bin/pyang", line 372, in run
    ctx.validate()
  File "(...)/lib/python3.8/site-packages/pyang/__init__.py", line 338, in validate
    statements.validate_module(self, m)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 409, in validate_module
    iterate(module, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 366, in iterate
    res = f(ctx, stmt)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 191, in <lambda>
    ('import', 'module'):lambda ctx, s: v_import_module(ctx, s),
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 612, in v_import_module
    submodule = add_module(i)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 597, in add_module
    validate_module(ctx, m)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 409, in validate_module
    iterate(module, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 401, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 397, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 397, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 397, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 401, in iterate
    iterate(s, phase)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 366, in iterate
    res = f(ctx, stmt)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 233, in <lambda>
    ('reference_2', 'when'):lambda ctx, s:v_reference_when(ctx, s),
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 2053, in v_reference_when
    v_xpath(ctx, stmt)
  File "(...)/lib/python3.8/site-packages/pyang/statements.py", line 2062, in v_xpath
    xpath.v_xpath(ctx, stmt, node)
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 84, in v_xpath
    chk_xpath_expr(ctx, stmt.i_orig_module, stmt.pos, node, node, q)
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 106, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[2])
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 99, in chk_xpath_expr
    chk_xpath_path(ctx, mod, pos, initial, 'root', q[1])
  File "(...)/lib/python3.8/site-packages/pyang/xpath.py", line 249, in chk_xpath_path
    p = data_node_up(node)
  File "(...)/lib/python3.8/site-packages/pyang/util.py", line 169, in data_node_up
    p = node.parent
AttributeError: 'str' object has no attribute 'parent'
```

**Comment by niktto** [comment]
I would love to dig deeper into this and try to prepare a PR with a fix but I'm not sure what is the intended output for this case. I would appreciate any guidance on what should be returned or how that case should be handled.

**Comment by niktto** [comment]
@mbj4668 ok, I think the yang file does not make sense, `/../../test/protocol` is a path that tries to go back from `/` in filesystem. After fixing the path (to `../../test/protocol`) it does not raise an error.

I think it still should not throw an exception but it does this only on a broken file.
