### ISSUE TITLE
AttributeError: 'str' object has no attribute 'i_identities'

### ISSUE THREAD

**Issue by verthezpw** [mbj4668/pyang#647]
See the following example model:
[example.zip](https://github.com/mbj4668/pyang/files/4850484/example.zip)

This fails in pyang with the following exception:

Traceback (most recent call last):
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/bin/pyang", line 533, in <module>
    run()
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/bin/pyang", line 401, in run
    ctx.validate()
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/context.py", line 331, in validate
    statements.validate_module(self, m)
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/statements.py", line 413, in validate_module
    iterate(module, phase)
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/statements.py", line 370, in iterate
    res = f(ctx, stmt)
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/statements.py", line 207, in <lambda>
    ('type_2', 'leaf'):lambda ctx, s: v_type_leaf(ctx, s),
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/statements.py", line 1015, in v_type_leaf
    defval, ' for the default value')
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/types.py", line 1022, in validate
    t_val = t.i_type_spec.str_to_val([], pos, val, module)
  File "/home/verthezp/local/pyang/pyang-pyang-2.3.0/pyang/types.py", line 266, in str_to_val
    if name not in pmodule.i_identities:
AttributeError: 'str' object has no attribute 'i_identities'

It looks like some calls in statements.py to the validate method are actually missing the module argument, so in the above case " for the default value" is taken as module, causing the exception.

This is failing in 2.3.0, and was apparently also already failing in 2.2.1.   In 1.7.5 it was succeeding.

**Comment by fredgan** [comment]
Hi,
Thanks. It has been fixed and should be OK now. Please try again using the latest master branch.

**Comment by verthezpw** [comment]
I've verified that this is fixed, thanks!
