### ISSUE TITLE
Yang Tree generation Error

### ISSUE THREAD

**Issue by masif-cs** [mbj4668/pyang#657]
Hi,

Recently I updated my pyang to latest version and started getting following error while generating yangtree. Can you please help me out?

Traceback (most recent call last):
  File "/usr/bin/pyang", line 5, in <module>
    pkg_resources.run_script('pyang==2.3.2', 'pyang')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/EGG-INFO/scripts/pyang", line 533, in <module>
    run()
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/EGG-INFO/scripts/pyang", line 401, in run
    ctx.validate()
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/context.py", line 331, in validate
    statements.validate_module(self, m)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 413, in validate_module
    iterate(module, phase)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 370, in iterate
    res = f(ctx, stmt)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 201, in <lambda>
    ('type', 'must'):lambda ctx, s: v_type_must(ctx, s),
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/statements.py", line 1381, in v_type_must
    xpath.v_xpath(ctx, stmt, None)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/xpath.py", line 84, in v_xpath
    chk_xpath_expr(ctx, stmt.i_orig_module, stmt.pos, node, node, q, None)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/xpath.py", line 119, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[1], t)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/xpath.py", line 117, in chk_xpath_expr
    chk_xpath_function(ctx, mod, pos, initial, node, q[1], q[2])
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/xpath.py", line 198, in chk_xpath_function
    chk_xpath_expr(ctx, mod, pos, initial, node, arg, signature[0][i])
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/xpath.py", line 119, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[1], t)
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/xpath.py", line 117, in chk_xpath_expr
    chk_xpath_function(ctx, mod, pos, initial, node, q[1], q[2])
  File "/usr/lib/python2.7/site-packages/pyang-2.3.2-py2.7.egg/pyang/xpath.py", line 198, in chk_xpath_function
    chk_xpath_expr(ctx, mod, pos, initial, node, arg, signature[0][i])
IndexError: list index out of range

**Comment by fredgan** [comment]
Hi, would you mind providing a model to reproduce this issue?

**Comment by masif-cs** [comment]
[_3gpp-common-managed-element.zip](https://github.com/mbj4668/pyang/files/4993589/_3gpp-common-managed-element.zip)

**Comment by masif-cs** [comment]
[o-ran-operations.zip](https://github.com/mbj4668/pyang/files/4993799/o-ran-operations.zip)

**Comment by fredgan** [comment]
@masif-cs Thanks for your reporting. It should be fixed now. Please try again with the latest master branch
