### ISSUE TITLE
JSONXSL plugin error

### ISSUE THREAD

**Issue by rawat-he** [mbj4668/pyang#667]
Hi,

I am getting below error when trying convert YANG models to XSL schema.

`Pyang version: 2.3.2`

Command:
`pyang --lax-quote-checks -f jsonxsl files/*.yang -o yang.xsl`

Error
```
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 533, in <module>
    run()
  File "/usr/local/bin/pyang", line 502, in run
    emit_obj.emit(ctx, modules, fd)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 93, in emit
    self.process_module(module)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 113, in process_module
    self.process_children(yam, "//nc:*", 1)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 170, in process_children
    self.process_children(ch, p, level + offset)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 170, in process_children
    self.process_children(ch, p, level + offset)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 170, in process_children
    self.process_children(ch, p, level + offset)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 167, in process_children
    self.type_param(ch, ct)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 175, in type_param
    types = self.get_types(node)
  File "/usr/local/lib/python3.6/site-packages/pyang/plugins/jsonxsl.py", line 219, in get_types
    resolve(node.i_leafref_ptr[0].search_one("type"))
TypeError: 'NoneType' object is not subscriptable	
```
I was also able to overcome the above error by adding simple check like below in `jsonxsl.py` function `get_types`
```
# if typ.arg == "leafref":
if typ.arg == "leafref" and node.i_leafref_ptr is not None:
    resolve(node.i_leafref_ptr[0].search_one("type"))
else:
    resolve(typ)
```
I am not sure if its a bug or intended functionality but with above changes XSL schema gets generated followed by JSON file.

Can anyone please confirm what should be done for this issue?

**Comment by fredgan** [comment]
Hi Himanshu, @rawat-he , Would you mind providing the yang file(or a simplified yang file) to reproduce this issue?

**Comment by rawat-he** [comment]
Hi Fred, @fredgan,

Please find attached the simplified yang file

[sample.yang.log](https://github.com/mbj4668/pyang/files/5094024/sample.yang.log)

**Comment by fredgan** [comment]
@rawat-he Hi, Sorry that your `sample.yang` can not reproduce your issue. After fixing some errors in the yang file, it works fine.

**Comment by rawat-he** [comment]
@fredgan Hi,

Can you please share what error fixes were done in ```sample.yang``` file?

Would appreciate it 👍

**Comment by fredgan** [comment]
@rawat-he 
Hi, I do the modifications as follows,

- Remove two unused import modules. 
- Add `leaf action-id` in list `progress-report`

```yang
module sample {
  yang-version 1.1;
  namespace my:sample;
  prefix mysample;

  import ietf-inet-types { prefix inet; }

  typedef on-off {
    type enumeration {
      enum on {  value 1; }
      enum off { value 0; }
    }
    description "";
  }
   container test {
		list backup {
			key id;
			description "";

			leaf id {
				type string;
				description "";
			}
			leaf auto-export {
				type on-off ;
				default off ;
				description "";
			}
			leaf auto-export-uri {
				type inet:uri;
				must '../auto-export = "false" or .' ;
				description "";
			}
			list progress-report {
				key action-id;
				config false;
				max-elements 1;
				description "";
				leaf action-id {
				    type string;
				}
			}
			action create-backup {
				description "";
				input {
					leaf name {
                        type string;
                        description "";
					}
				}
				output {
					leaf return-value {
                        type leafref {
                            path "../../progress-report/action-id" ;
                        }
                        mandatory true;
                        description "";
					}
				}
			}
		}
   }
}
```

**Comment by rawat-he** [comment]
Closing the issue and thank you @fredgan for your prompt responses.
