### ISSUE TITLE
failure in processing uses

### ISSUE THREAD

**Issue by mrehder** [mbj4668/pyang#690]
v2.3.2 pyang

I am getting this failure, using pyang to generate a yin file. 
Seems to be something in uses processing.
This happened in an older version as well.

```
Traceback (most recent call last):
  File "/usr/bin/pyang", line 533, in <module>
    run()
  File "/usr/bin/pyang", line 401, in run
    ctx.validate()
  File "/usr/lib/python3.6/site-packages/pyang/context.py", line 331, in validate
    statements.validate_module(self, m)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 413, in validate_module
    iterate(module, phase)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 370, in iterate
    res = f(ctx, stmt)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 190, in <lambda>
    ('import', 'module'):lambda ctx, s: v_import_module(ctx, s),
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 608, in v_import_module
    module = add_module(i)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 599, in add_module
    validate_module(ctx, m)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 413, in validate_module
    iterate(module, phase)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 370, in iterate
    res = f(ctx, stmt)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 190, in <lambda>
    ('import', 'module'):lambda ctx, s: v_import_module(ctx, s),
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 608, in v_import_module
    module = add_module(i)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 599, in add_module
    validate_module(ctx, m)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 413, in validate_module
    iterate(module, phase)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 370, in iterate
    res = f(ctx, stmt)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 190, in <lambda>
    ('import', 'module'):lambda ctx, s: v_import_module(ctx, s),
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 608, in v_import_module
    module = add_module(i)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 599, in add_module
    validate_module(ctx, m)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 413, in validate_module
    iterate(module, phase)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 370, in iterate
    res = f(ctx, stmt)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 210, in <lambda>
    ('expand_1', 'module'):lambda ctx, s: v_expand_1_children(ctx, s),
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 1455, in v_expand_1_children
    v_expand_1_uses(ctx, s)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 1501, in v_expand_1_uses
    v_expand_1_children(ctx, stmt.i_grouping)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 1464, in v_expand_1_children
    v_expand_1_children(ctx, s)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 1455, in v_expand_1_children
    v_expand_1_uses(ctx, s)
  File "/usr/lib/python3.6/site-packages/pyang/statements.py", line 1494, in v_expand_1_uses
    if stmt.i_grouping is None:
AttributeError: i_grouping
```

**Comment by mrehder** [comment]
I'm trying to undo recent changes to see if I can isolate the cause. I think the problem is the presence of a leafref within a grouping. I'll keep testing variations...

**Comment by fredgan** [comment]
@mrehder Hi, will you mind providing the YANG models reproducing this?

**Comment by mrehder** [comment]
found it...

compile "test.yang" attached 
[test.txt](https://github.com/mbj4668/pyang/files/5464596/test.txt)
[test2.txt](https://github.com/mbj4668/pyang/files/5464597/test2.txt)

and you get the above failure. Seems that a reference back to the original module with two levels of grouping in the orginal causes the error.

**Comment by mrehder** [comment]
Provided (hadn't hit "Comment" button yet...)

**Comment by fredgan** [comment]
Thanks for reporting. It's been fixed now.
