### ISSUE TITLE
Tuple index out of range error on XPath expression

### ISSUE THREAD

**Issue by verthezpw** [mbj4668/pyang#699]
See the attached model 
[example.zip](https://github.com/mbj4668/pyang/files/5537033/example.zip)

Pyang (2.2.1, 2.3.0, 2.4.0) fails on this model with the following exception, although the XPath seems to be valid:
Traceback (most recent call last):
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/bin/pyang", line 533, in <module>
    run()
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/bin/pyang", line 401, in run
    ctx.validate()
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/context.py", line 331, in validate
    statements.validate_module(self, m)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/statements.py", line 413, in validate_module
    iterate(module, phase)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/statements.py", line 408, in iterate
    iterate(s, phase)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/statements.py", line 370, in iterate
    res = f(ctx, stmt)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/statements.py", line 201, in <lambda>
    ('type', 'must'):lambda ctx, s: v_type_must(ctx, s),
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/statements.py", line 1381, in v_type_must
    xpath.v_xpath(ctx, stmt, None)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 84, in v_xpath
    chk_xpath_expr(ctx, stmt.i_orig_module, stmt.pos, node, node, q, None)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 119, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[1], t)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 106, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[2], None)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 119, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[1], t)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 117, in chk_xpath_expr
    chk_xpath_function(ctx, mod, pos, initial, node, q[1], q[2])
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 199, in chk_xpath_function
    chk_xpath_expr(ctx, mod, pos, initial, node, arg, args_signature[i])
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 119, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[1], t)
  File "/home/verthezp/local/pyang/pyang-pyang-2.4.0/pyang/xpath.py", line 122, in chk_xpath_expr
    chk_xpath_expr(ctx, mod, pos, initial, node, q[3], None)
IndexError: tuple index out of range

**Comment by fredgan** [comment]
Hi Peter @verthezpw , it should be fixed now. Please try with the latest master branch. Thanks for reporting.

**Comment by verthezpw** [comment]
Thanks, confirmed fixed on master.
