### ISSUE TITLE
Not generating the yang module to jsonschema 

### ISSUE THREAD

**Issue by rahul12130** [mbj4668/pyang#873]
pyang --plugindir ../ -f jsonschema ./test-module.yang > test-module.jsonschema
Traceback (most recent call last):
  File "/home/abcd/pyang/bin/pyang", line 4, in <module>
    from pyang.scripts.pyang_tool import run
  File "/home/abcd/pyang/pyang/scripts/pyang_tool.py", line 9, in <module>
    from pathlib import Path
ImportError: No module named pathlib

getting import error

**Comment by mbj4668** [comment]
This seems to be a python problem.  `pathlib` is a standard python module.
