### ISSUE TITLE
pyang cannot run in Python 3.12 (pkg_resources)

### ISSUE THREAD

**Issue by JennToo** [mbj4668/pyang#911]
```
Traceback (most recent call last):
  File "/tmp/build/.porg/venvs/3.12-d/bin/pyang", line 5, in <module>
    from pyang.scripts.pyang_tool import run
  File "/tmp/build/.porg/venvs/3.12-d/lib/python3.12/site-packages/pyang/scripts/pyang_tool.py", line 12, in <module>
    from pyang import plugin
  File "/tmp/build/.porg/venvs/3.12-d/lib/python3.12/site-packages/pyang/plugin.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

`pkg_resources` has been deprecated for a while now and was finally removed in 3.12 it seems.

**Comment by 991jo** [comment]
I ran into the same problem when my default venv was created with setuptools version 69.
When I upgraded it via `pip install --upgrade setuptools` to 72.2.0 it worked again.

**Comment by cpascual** [comment]
`pkg_resources` [can  be replaced by `importlib.resources`](https://importlib-resources.readthedocs.io/en/latest/migration.html) which is available since python 3.7 (the oldest version supported by pyang)

Note: I ran into this using python **3.11** but installing with  [uv](https://docs.astral.sh/uv) which does not install setuptools by default:

```console
$ uvx  pyang --version
Traceback (most recent call last):
  File "/home/carlos/.cache/uv/archive-v0/mlcOb-HMgtjthDNgvqnV3/bin/pyang", line 7, in <module>
    from pyang.scripts.pyang_tool import run
  File "/home/carlos/.cache/uv/archive-v0/mlcOb-HMgtjthDNgvqnV3/lib/python3.12/site-packages/pyang/scripts/pyang_tool.py", line 12, in <module>
    from pyang import plugin
  File "/home/carlos/.cache/uv/archive-v0/mlcOb-HMgtjthDNgvqnV3/lib/python3.12/site-packages/pyang/plugin.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

A workaround that works for me is:

```console
$ uvx --with setuptools pyang --version
pyang 2.6.1
```

IMHO this is a bug in pyang because it uses `pkg_resources` without declaring `setuptools` as a dependency.

**Comment by mbj4668** [comment]
It seems it doesn't work the same put of the box in 3.8 and 3.9.  But we can use it from 3.10.

**Comment by LewisGaul** [comment]
The dependency on setuptools isn't really the problem, it's that it's not listed in the project's dependencies. So could it be added (preferably only for those older Python version where it's needed)?

**Comment by jillesca** [comment]
[> pip install --upgrade setuptools](https://github.com/mbj4668/pyang/issues/911#issuecomment-2287927376)

This fixed it for me. Running `Python 3.13.1`
